version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/services-api/
    command: go run main.go
    working_dir: /services-api/cmd
    depends_on:
      services-psql:
        condition: service_healthy
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
  
  services-psql:  
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=services
    volumes:
      - ./storage:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
